[profile.default]
src = "src"
optimizer = true
optimizer_runs = 200
out = "out"
libs = ["lib"]
gas_reports = ["Raffle"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts",
    "@solmate=lib/solmate/src"
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" }
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[fuzz]
runs = 1000